# .NET Core Troubleshooting (Application Crash)

This article outlines the steps to troubleshoot Application Crash issue in a .NET Core application.

## Problem

Application Crash is an issue where the application terminates unexpectedly due to an unhandled exception or catastrophic failure (e.g. Out Of Memory, Heap Corruption). The goal of troubleshooting such issue is to identify the source of the exception and gather additional details to be able to resolve the problem.

Let's review the following sample code:

```
protected override void Execute()
{
    WriteInformation("Application crash started ...");
    if (ThrowException)
        throw new UnhandledException("Application crash.");
    Thread.CurrentThread.Interrupt();
    Wait();
}

public void WriteInformation(string text) => Console.WriteLine(text);

public void Wait(TimeSpan interval)
{
    WriteInformation("Press any key to continue ...");
    while (!Console.KeyAvailable)
        Thread.Sleep(interval);
    Console.ReadKey(true);
}
```

In the code snippet above, the main function `Execute()` contains a `Thread.CurrentThread.Interrupt()` call. The `Thread.Interrupt()` method throws a `ThreadInterruptedException` and terminates the main thread. The purpose of this sample is to simulate a more non-deterministic application termination. If we were to use `throw new Exception()` or `Environment.FailFast()` and make sure there is no exception handling logic, the application would display the exception message along with the stack trace. In most cases, that information would be sufficient to troubleshoot the crash. The `Thread.Interrupt()` in this scenario generates `ThreadInterruptedException`, which is raised at a later point following the `Thread.Interrupt()` method invocation.

## Prerequisites

In order to investigate the issue, we need to take a core dump at the time of the crash immediately before the application is terminated. To create a core dump in this case, we set the following environment variables prior to starting the application: 

```
export DOTNET_DbgEnableMiniDump=1
export DOTNET_DbgMiniDumpType=4
export DOTNET_DbgMiniDumpName=/tmp/CoreDump.%p
```

This setup will generate a full core dump on application crash located at `/tmp/CoreDump.<PID>`, where `<PID>` is the application process ID.

Once we run the application, we should see an output similar to:

```
Application crash started ...
Press any key to continue ...
[createdump] Gathering state for process 4188 dotnet
[createdump] Crashing thread 105c signal 6 (0006)
[createdump] Writing full dump to file /tmp/CoreDump.4188
[createdump] Written 185233408 bytes (45223 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 347ms
Aborted
```

The output shows that a core dump was created into `/tmp/CoreDump.4188` and the application was terminated (`Aborted`).

## Analysis

We start the application crash analysis by looking at the managed threads:

```
clrthreads
```

Output:
```
ThreadCount:      5
UnstartedThread:  0
BackgroundThread: 4
PendingThread:    0
DeadThread:       0
Hosted Runtime:   no
                                                                                                            Lock  
 DBG   ID     OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
   1    1     105c 00005618AC893410    20020 Preemptive  00007EF35A8B5FA0:00007EF35A8B7118 00005618AC8820A0 -00001 Ukn System.Threading.ThreadInterruptedException 00007ef35a8b5c38
   6    2     1061 00005618AC89D800    21220 Preemptive  0000000000000000:0000000000000000 00005618AC8820A0 -00001 Ukn (Finalizer) 
   7    3     1062 00005618AC8F2EB0    21220 Preemptive  0000000000000000:0000000000000000 00005618AC8820A0 -00001 Ukn 
   8    4     1063 00005618AC971170    21220 Preemptive  00007EF35A83B190:00007EF35A83D090 00005618AC8820A0 -00001 Ukn 
   9    5     1064 00005618AC9C6760  2021220 Preemptive  0000000000000000:0000000000000000 00005618AC8820A0 -00001 Ukn
```

The output above shows that Thread ID `1` has `System.Threading.ThreadInterruptedException` instance at address `0x00007EF35A8B5C38`. Thread ID `1` is the main application thread, since the System Thread ID (OSID = `0x105C`) and the Process ID (PID = `4188`) are the same. An unhandled exception in the main application thread would explain why the application terminates unexpectedly.

Next, we can get more details about the `ThreadInterruptedException` at `0x00007EF35A8B5C38`:

```
printexception 0x00007EF35A8B5C38
```

Output:
```
Exception object: 00007ef35a8b5c38
Exception type:   System.Threading.ThreadInterruptedException
Message:          Thread was interrupted from a waiting state.
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    00007FFC2C056EA0 00007F336DCA82D9 System.Private.CoreLib.dll!System.Threading.Thread.Sleep(Int32)+0x39
    00007FFC2C056F40 00007F336EA61BD1 ByteZoo.Blog.Common.dll!ByteZoo.Blog.Common.Services.DisplayService.Wait(System.TimeSpan)+0x91
    00007FFC2C056F90 00007F336EA61AB9 ByteZoo.Blog.Common.dll!ByteZoo.Blog.Common.Services.DisplayService.Wait()+0x49
    00007FFC2C056FB0 00007F336EA61A11 ByteZoo.Blog.App.dll!ByteZoo.Blog.App.Controllers.Scenarios.Exceptions.CrashController.Execute()+0xd1
    00007FFC2C056FF0 00007F336EA61896 ByteZoo.Blog.App.dll!ByteZoo.Blog.App.Controllers.Controller.Execute(System.IServiceProvider)+0x56
    00007FFC2C057010 00007F336EA6181A ByteZoo.Blog.App.dll!ByteZoo.Blog.App.Program+<>c__DisplayClass0_0.<Main>b__0(ByteZoo.Blog.App.Controllers.Controller)+0x5a
    00007FFC2C057040 00007F336EA61768 CommandLine.dll!CommandLine.ParserResultExtensions.WithParsed[[System.__Canon, System.Private.CoreLib]](CommandLine.ParserResult`1<System.Object>, System.Action`1<System.__Canon>)+0xa8
    00007FFC2C057090 00007F336EA01B86 ByteZoo.Blog.App.dll!ByteZoo.Blog.App.Program.Main(System.String[])+0x326

StackTraceString: <none>
HResult: 80131519
```

The output shows that the `ThreadInterruptedException` was raised during the `Thread.Sleep()` execution. Although this stack trace is correct, it is incomplete and does not show the full picture.

> [!NOTE]
> The stack trace in `printexception` is calculated (generated) during debugging and in some cases might be empty (e.g. `ExecutionEngineException` from `Environment.FailFast()`).

To get the detailed managed stack trace, we use the following:

```
thread select 1
clrstack
```

Output:
```
OS Thread Id: 0x105c (1)
        Child SP               IP Call Site
00007FFC2C053330 00007f33ed2f2bd7 [InlinedCallFrame: 00007ffc2c053330] 
00007FFC2C053330 00007f336dcf6f34 [InlinedCallFrame: 00007ffc2c053330] 
00007FFC2C0532F0 00007F336DCF6F34 System.Runtime.EH.DispatchEx(System.Runtime.StackFrameIterator ByRef, ExInfo ByRef) [/_/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs @ 865]
00007FFC2C053430 00007F336DCF6730 System.Runtime.EH.RhThrowEx(System.Object, ExInfo ByRef) [/_/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs @ 645]
00007FFC2C056EB8 00007f33ecec2934 [InlinedCallFrame: 00007ffc2c056eb8] 
00007FFC2C056EB8 00007f336dca82cb [InlinedCallFrame: 00007ffc2c056eb8] 
00007FFC2C056EA0 00007F336DCA82CB System.Threading.Thread.Sleep(Int32) [/_/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.cs @ 368]
00007FFC2C056F40 00007F336EA61BD2 ByteZoo.Blog.Common.Services.DisplayService.Wait(System.TimeSpan) [/home/marian/Development/ByteZoo.Blog/Sources/ByteZoo.Blog.Common/Services/DisplayService.cs @ 96]
00007FFC2C056F90 00007F336EA61ABA ByteZoo.Blog.Common.Services.DisplayService.Wait() [/home/marian/Development/ByteZoo.Blog/Sources/ByteZoo.Blog.Common/Services/DisplayService.cs @ 81]
00007FFC2C056FB0 00007F336EA61A12 ByteZoo.Blog.App.Controllers.Scenarios.Exceptions.CrashController.Execute() [/home/marian/Development/ByteZoo.Blog/Sources/ByteZoo.Blog.App/Controllers/Scenarios/Exceptions/CrashController.cs @ 31]
00007FFC2C056FF0 00007F336EA61897 ByteZoo.Blog.App.Controllers.Controller.Execute(System.IServiceProvider) [/home/marian/Development/ByteZoo.Blog/Sources/ByteZoo.Blog.App/Controllers/Controller.cs @ 26]
00007FFC2C057010 00007F336EA6181B ByteZoo.Blog.App.Program+<>c__DisplayClass0_0.<Main>b__0(ByteZoo.Blog.App.Controllers.Controller) [/home/marian/Development/ByteZoo.Blog/Sources/ByteZoo.Blog.App/Program.cs @ 33]
00007FFC2C057040 00007F336EA61769 CommandLine.ParserResultExtensions.WithParsed[[System.__Canon, System.Private.CoreLib]](CommandLine.ParserResult`1<System.Object>, System.Action`1<System.__Canon>)
```

The output shows that after the `Thread.Sleep()` call, there are two native stack frames (`[InlinedCallFrame: 00007ffc2c056eb8]`) and then two managed exception dispatch stack frames (`System.Runtime.EH.RhThrowEx()` and `System.Runtime.EH.DispatchEx()`).

> [!NOTE]
> The inner workings of the `Thread.Interrupt()` and the CLR thread exception propagation logic is outside the scope of this article.

To get the missing native stack trace, we use the following:

```
bt
```

Output:
```
* thread #1, name = 'dotnet', stop reason = signal SIGABRT
    ...
    frame #14: 0x00007f33ecdf8ddc libcoreclr.so`DispatchManagedException(throwable=<unavailable>, pExceptionContext=0x00007ffc2c0561b0) at exceptionhandling.cpp:5697:5 [opt]
    frame #15: 0x00007f33ecdf9286 libcoreclr.so`DispatchManagedException(throwable=0x00007ef35a8b5c38) at exceptionhandling.cpp:5714:5 [opt]
    frame #16: 0x00007f33ecc2b8f1 libcoreclr.so`UnwindAndContinueRethrowHelperAfterCatch(pEntryFrame=<unavailable>, pException=<unavailable>, nativeRethrow=false) at excep.cpp:7509:13 [opt]
    frame #17: 0x00007f33ecd192b8 libcoreclr.so`::ThreadNative_Sleep(iTime=<unavailable>) at comsynchronizable.cpp:993:5 [opt]
    ...
    frame #49: 0x00005618a6730dd9 dotnet`_start + 41
```

The native stack trace shows that, after the `ThreadNative_Sleep()` frame, there is a call to `DispatchManagedException()` with parameter `throwable=0x00007ef35a8b5c38` which matches the `ThreadInterruptedException` instance address of `0x00007EF35A8B5C38`.

At this point, we have identified a `ThreadInterruptedException` raised on the main thread, which causes the application to stop. We also have the full list of methods - both managed and native, which are part of the main application thread call stack.

## Conclusion

The resolution of the application crash depends on the type of exception that causes it. If the exception has an immediate effect (e.g. `IndexOutOfRangeException`, `ArgumentNullException`) the focus is on the last method (stack frame) that contains the exception.

In this scenario, the exception has a delayed effect. This means that the issue has started earlier and manifests itself later in the call stack. The same applies to Out Of Memory (`OutOfMemoryException`) and Heap Corruption (`AccessViolationException`) exceptions.

To resolve this particular Application Crash, we have to analyze all calls in the thread that contains the `ThreadInterruptedException` instance. We start from the top of the stack (last method invocation) and look for `Thread.Interrupt()` calls as follows:

* `System.Threading.Thread.Sleep(Int32)`: No `Thread.Interrupt()` calls.
* `ByteZoo.Blog.Common.Services.DisplayService.Wait(System.TimeSpan)`: No `Thread.Interrupt()` calls.
* `ByteZoo.Blog.Common.Services.DisplayService.Wait()`: No `Thread.Interrupt()` calls.
* `ByteZoo.Blog.App.Controllers.Scenarios.Exceptions.CrashController.Execute()`: This method contains a `Thread.CurrentThread.Interrupt()` call.

Once we have identified the source of the Application Crash - `Thread.Interrupt()` invocation inside the `Execute()` method - we can focus on changing the application logic to resolve the problem.

## References

* [.NET Core Concepts (Summary)](/Resources/Articles/Concepts/.NET%20Core%20Concepts%20(Summary).md)
* [.NET Core Troubleshooting (Hub)](/Resources/Articles/Troubleshooting/.NET%20Core%20Troubleshooting%20(Hub).md)
* [Article Source Code](/Sources)

<!--- Category = Tags = .NET Core, .NET Troubleshooting, .NET Analysis, Linux --->